title: Project
files: true
pages: false
files:
  fields:
    # caption:
    #   label: Caption
    #   type: textarea
    #   buttons:
    #     - link
    #     - email
    # contentsize:
    #   label: Size
    #   type: radio
    #   default: fullscreen
    #   options:
    #     contain: Contain
    #     fullscreen: Fullscreen
    #   columns: 2
    # videolink:
    #   label: Video ID
    #   type: text
    #   icon: code
    #   help: Youtube ID or Vimeo ID
    # vendor:
    #   label: Vendor
    #   type: radio
    #   default: vimeo
    #   options:
    #     vimeo: Vimeo 
    #     youtube: Youtube
    # videostream:
    #   label: Video external stream link (.m3u8)
    #   type: url
    # videoexternal:
    #   label: Video external file link
    #   type: url
    # videofile:
    #   label: Video File
    #   type: select
    #   options: videos
fields:
  prevnext: prevnext
  title:
    label: Title
    type:  text
  featured:
    label: Featured image 1
    type: image
    width: 1/3
  featured2:
    label: Featured image 2
    type: image
    width: 1/3
  featured3:
    label: Featured image 3
    type: image
    width: 1/3
  subtitle:
    label: Subtitle
    type: text
    width: 3/4
  date:
    label: Year
    type:  date
    format: YYYY
    required: true
    width: 1/4
  influencers:
    label: Influencers
    type:  text
    width: 1/3
  impressions:
    label: Impressions
    type:  text
    width: 1/3
  engagement:
    label: Engagement rate
    type:  text
    width: 1/3
  text:
    label: Description
    type: textarea
  medias: 
    label: Images
    type: images
