title: Site
pages:
  template:
    - default
    - manifesto
    - entries
    - projects
    - events
    - offices
fields:
  generalSettings:
    label: Site Settings
    type: headline
  title:
    label: Title
    type:  text
  description:
    label: Description
    type:  textarea
  keywords:
    label: Keywords
    type:  tags
  customcss:
    label: Custom CSS
    type: textarea
    buttons: false
  googleAnalytics:
    label: Google Analytics ID
    type: text
    icon: code
    help: Tracking ID in the form UA-XXXXXXXX-X. Keep this field empty if you are not using it.
    width: 1/2
  ogimage:
    label: Facebook OpenGraph image
    type: image
    help: 1200x630px minimum
    width: 1/2
  links:
    label: Links
    type: structure
    style: table
    fields:
      url:
        label: URL
        type: url
      title:
        label: Title
        type: text
  contact:
    label: Contact
    type:  textarea
  socials:
    label: Socials
    type: structure
    style: table
    fields:
      url:
        label: URL
        type: url
      title:
        label: Title
        type: text